package edu.umich.gopalkri.wakeup.data;

import edu.umich.gopalkri.wakeup.WakeUpException;

public class Alarm implements java.io.Serializable
{
    public static final String FIELD_SEPARATOR = "@@@@@";

    public enum Units
    {
        KM, METERS, MILES, FEET
    }

    public static int UnitsToInt(Units unit)
    {
        switch (unit)
        {
        case KM:
            return 0;
        case METERS:
            return 1;
        case MILES:
            return 2;
        case FEET:
            return 4;
        default:
            return -1;
        }
    }

    public static String UnitsToString(Units unit)
    {
        switch (unit)
        {
        case KM:
            return "km";
        case METERS:
            return "meters";
        case MILES:
            return "miles";
        case FEET:
            return "feet";
        default:
            return null;
        }
    }

    public static Units IntToUnits(int unit) throws InvalidAlarmStringException
    {
        switch (unit)
        {
        case 0:
            return Units.KM;
        case 1:
            return Units.METERS;
        case 2:
            return Units.MILES;
        case 3:
            return Units.FEET;
        default:
            return null;
        }
    }

    public class InvalidAlarmStringException extends WakeUpException
    {
        /**
         * Autogenerated.
         */
        private static final long serialVersionUID = 8770589743483321463L;
    }

    public Alarm()
    {}

    public Alarm(String alarmStr) throws InvalidAlarmStringException
    {
        String split[] = alarmStr.split(FIELD_SEPARATOR);
        if (split.length != 5)
        {
            throw new InvalidAlarmStringException();
        }
        name = split[0];
        try
        {
            latitude = Double.parseDouble(split[1]);
            longitude = Double.parseDouble(split[2]);
            radius = Double.parseDouble(split[3]);
            unit = IntToUnits(Integer.parseInt(split[4]));
        }
        catch (NumberFormatException e)
        {
            throw new InvalidAlarmStringException();
        }
        if (unit == null)
        {
            throw new InvalidAlarmStringException();
        }
    }

    public Alarm(String name, double latitude, double longitude, double radius, Units unit)
            throws InvalidAlarmNameException
    {
        if (name.contains(FIELD_SEPARATOR))
        {
            throw new InvalidAlarmNameException();
        }
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.radius = radius;
        this.unit = unit;
    }

    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append(name);
        sb.append(FIELD_SEPARATOR);
        sb.append(latitude);
        sb.append(FIELD_SEPARATOR);
        sb.append(longitude);
        sb.append(FIELD_SEPARATOR);
        sb.append(radius);
        sb.append(FIELD_SEPARATOR);
        sb.append(UnitsToInt(unit));
        return sb.toString();
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name) throws InvalidAlarmNameException
    {
        if (name.contains(FIELD_SEPARATOR))
        {
            throw new InvalidAlarmNameException();
        }
        this.name = name;
    }

    public double getLatitude()
    {
        return latitude;
    }

    public void setLatitude(double latitude)
    {
        this.latitude = latitude;
    }

    public double getLongitude()
    {
        return longitude;
    }

    public void setLongitude(double longitude)
    {
        this.longitude = longitude;
    }

    public double getRadius()
    {
        return radius;
    }

    public void setRadius(double radius)
    {
        this.radius = radius;
    }

    public double getRadiusInMeters()
    {
        switch (unit)
        {
        case KM:
            return radius * 1E3;
        case METERS:
            return radius;
        case MILES:
            return radius * 1609.344; // 1 mile = 1609.344 meters.
        case FEET:
            return radius * 0.3048; // 1 foot = 0.3048 meters.
        }
        // Should never happen.
        return -1;
    }

    public Units getUnit()
    {
        return unit;
    }

    public void setUnit(Units unit)
    {
        this.unit = unit;
    }

    private String name;

    private double latitude;

    private double longitude;

    private double radius;

    private Units unit;

    /**
     * Autogenerated.
     */
    private static final long serialVersionUID = -492202907798984554L;
}
