package edu.umich.gopalkri.wakeup.data;

import edu.umich.gopalkri.wakeup.WakeUpException;

public class AlarmAlreadyExistsException extends WakeUpException
{
    /**
     * Autogenerated.
     */
    private static final long serialVersionUID = 9170076316622455534L;
}
