/*
Copyright (C) 2009 Gopalkrishna Sharma.
Email: gopalkri@umich.edu / gopalkrishnaps@gmail.com

This file is part of WakeUp!.

Wake Up! is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Wake Up! is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Wake Up!.  If not, see <http://www.gnu.org/licenses/>.
*/

package edu.umich.gopalkri.wakeup.data;

import edu.umich.gopalkri.wakeup.WakeUpException;

/**
 * Thrown when an Alarm's String representation is invalid.
 * @author Gopalkrishna Sharma
 */
public class InvalidAlarmStringException extends WakeUpException
{
    /**
     * Autogenerated.
     */
    private static final long serialVersionUID = -4876422804675518199L;
}
