package edu.umich.gopalkri.wakeup.data;

import edu.umich.gopalkri.wakeup.WakeUpException;

public class InvalidAlarmNameException extends WakeUpException
{
    /**
     * Autogenerated.
     */
    private static final long serialVersionUID = -471401428188215981L;
}
