package edu.umich.gopalkri.wakeup.data;

import edu.umich.gopalkri.wakeup.WakeUpException;

public class InvalidAlarmStringException extends WakeUpException
{
    /**
     * Autogenerated.
     */
    private static final long serialVersionUID = -4876422804675518199L;
}
